mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sesshandl.urls')),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

sesshandl/urls.py
from django.urls import include, path
from django.contrib.auth import urls
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path('accouns/login', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/signup', views.signup, name='signup'),
    #path('/signup', 'registratiion/signup.html', name='signup')
]

polls/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

sesshandl/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.decorators import login_required

from .models import Question, Choice


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '../accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'


    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = "../../accounts/login"
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(LoginRequiredMixin, generic.DetailView):
    login_url = "../../../accounts/login"
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/results.html', {
            'question': question,
            'error_message': "You didn't select a choice.",

        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

sesshandl/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('../polls/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

polls/templates/polls/detail.html
<head>
  <title> PolZapp: Quelle est votre opinion ? </title>

  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'polls/mdl1.3.0/material.min.css' %}" />
  <script src="{% static 'polls/mdl1.3.0/material.min.js' %}"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'sesshandlr/styles.css' %}"/>
</head>

<body class="sess-body">
  <div class="site-container">

    <h3>You're answering</h3>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for='choice{{ forloop.counter }}' style="margin: 8px 15px">
        <input class="mdl-radio__button" type='radio' name='choice' id='choice{{ forloop.counter }}' value='{{ choice.id }}'/>
        <span class="mdl-radio__label"><p>{{ choice.choice_text }}</p></span>
      </label>
      <br/>
    {% endfor %}
    <br/>
    <input style="margin-top: 20px;" class="mdl-button mdj-js-button mdl-button--raised mdl-button--primary" type='submit' value='Vote' />

    <br/>
    </form>
    <a href="{% url 'polls:index' %}"  style="text-align: center">Go Back
    </a>
  </div>
</body>

polls/templates/polls/index.html
<head>
  <title> PolZapp: Quelle est votre opinion ? </title>

  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'polls/mdl1.3.0/material.min.css' %}" />
  <script src="{% static 'polls/mdl1.3.0/material.min.js' %}"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'sesshandlr/styles.css' %}"/>
</head>

<body class="sess-body">
  <div class="site-container">
    <h1 class='logo'> Lorem.ipsum </h1>
    <h3 class='subtitle'> Share your opinions </h3>
    <br/>
    {% if user.is_authenticated %}
      <h5 style='margin-left: 20px;'> Hello, {{ user.get_username }} !</h5>
    {% else %}
      <!-- dev purposes only -->
      <a href="{% url 'login'%}?next={{request.path}}">Login</a>
    {% endif %}
    {% if latest_question_list %}
        <ul class='mdl-list'>
            {% for question in latest_question_list %}
                <li class='mdl-list__item'>
                    <i class="material-icons mdl-list__item-icon listicon">poll</i>
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls available.</p>
    {% endif %}

    {% if user.is_authenticated %}
      <a class="mdl-button mdl-js-button mdl-button--accent" href="{% url 'logout'%}">Log Out</a>
    {% else %}
    {% endif %}
  </div>
</body>

polls/templates/polls/results.html
<head>
  <title> PolZapp: Quelle est votre opinion ? </title>

  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'polls/mdl1.3.0/material.min.css' %}" />
  <script src="{% static 'polls/mdl1.3.0/material.min.js' %}"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'sesshandlr/styles.css' %}"/>
</head>

<body class="sess-body">
  <div class="site-container">
    <h3>See what others answered for</h3>
    <h1>{{ question.question_text }}</h1>

    <div style='display: table; width:100%; margin-left: 20px'>
      {% for choice in question.choice_set.all %}
          <div style='display: table-row'>
            <div style='display: table-cell; max-width: 150px'><p>{{ choice.choice_text }}</p></div>
            <div style='display: table-cell; width: auto'><p>{{ choice.votes }} vote{{ choice.votes|pluralize }}</p></div>
          </div>
      {% endfor %}
    </div>

    <a style="margin-top: 20px;" class="mdl-button mdj-js-button mdl-button--raised mdl-button--primary" href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <br/>
    <a style="margin-top: 10px;" class="mdl-button mdj-js-button mdl-button--raised mdl-button--accent" href="{% url 'polls:index' %}">Look at other polls</a>
  </div>
</body>

sesshandl/templates/sesshandl/index.html
this is the index